foundation: overturemaps
url: https://overturemaps.landscape2.io
categories:
  - name: Overture Maps Members
    subcategories:
      - Steering
      - General
      - Contributor
colors:
  color1: rgba(44, 46, 127, 1)
  color2: rgba(0, 180, 137, 1)
  color3: rgba(55, 105, 202, 1)
  color4: rgba(44, 46, 127, 1)
  color5: rgba(55, 105, 202, 0.8)
  color6: rgba(44, 46, 127, 0.8)
  color7: rgba(249, 254, 254, 1)
featured_items:
  - field: subcategory
    options:
      - value: Steering
footer:
  links:
    github: https://github.com/OvertureMaps
    homepage: https://overturemaps.org
    linkedin: https://www.linkedin.com/company/overture-maps-foundation
    twitter: https://twitter.com/OvertureMaps
  logo: https://overturemaps.org/wp-content/uploads/sites/16/2022/11/logo-vertical-white.svg
  text: >
    Copyright © 2024 The Linux Foundation®. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of
    The Linux Foundation, please see our [Trademark Usage page](https://www.linuxfoundation.org/trademark-usage). Linux is a registered trademark of Linus
    Torvalds. [Privacy Policy](https://www.linuxfoundation.org/privacy) and [Terms of Use](https://www.linuxfoundation.org/terms). This website contains data
    received from Crunchbase. This data is not licensed pursuant to the Apache License. It is subject to Crunchbase's Data Access Terms, available at
    <https://data.crunchbase.com/docs/terms>, and is only permitted to be used with Linux Foundation landscape projects.
grid_items_size: large
header:
  links:
    github: https://github.com/OvertureMaps/landscape
  logo: https://nextgis.com/wp-content/uploads/2024/05/omf.png
images:
  favicon: https://overturemaps.org/wp-content/uploads/sites/16/2022/12/cropped-Favicon-150x150.png
  open_graph: https://overturemaps.org/wp-content/uploads/sites/16/2022/12/cropped-Favicon-300x300.png
members_category: Overture Maps Members
screenshot_width: 1500
